# -*- coding: utf-8 -*-
"""Data_Analytics_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qw9jP2s2J_h-MgyuyJeGgQpxSK2HmIPV
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline
plt.rcParams["figure.figsize"] = (8, 5)

file_path = "/content/drive/MyDrive/Data_Analytics/Survey_Data_95_responses.xlsx"

shopping_data = pd.read_excel(file_path)
shopping_data.head()

print("Dataset shape (rows, columns):", shopping_data.shape)

print("\nColumn names:")
print(shopping_data.columns.tolist())

print("\nInfo about columns:")
shopping_data.info()

print("\nMissing values per column:")
print(shopping_data.isna().sum())

new_names = {
    "Timestamp": "timestamp",
    "Gender": "gender",
    "Age": "age_group",
    "How often do you shop online?": "shopping_frequency",
    "Preferences": "shopping_preference",
    '"Online shopping will replace physical stores in the future"': "online_will_replace_stores",
}

extra_names = [
    "website_quality_importance",
    "security_privacy_importance",
    "product_range_importance",
    "convenience_importance",
    "delivery_importance",
]

for idx, simple_name in zip(range(6, 11), extra_names):
    new_names[shopping_data.columns[idx]] = simple_name

shopping_data = shopping_data.rename(columns=new_names)
shopping_data.columns

print("Gender counts:\n", shopping_data["gender"].value_counts(), "\n")

print("Age group counts:\n", shopping_data["age_group"].value_counts(), "\n")

print("Shopping frequency counts:\n", shopping_data["shopping_frequency"].value_counts(), "\n")

print("Shopping preference counts:\n", shopping_data["shopping_preference"].value_counts())

def clean_likert_answer(text_value):
    """Map 'Extremely important' etc. to scores 1–5"""
    if pd.isna(text_value):
        return np.nan
    text = str(text_value).strip().lower()
    if "extremely important" in text:
        return 5
    if "very important" in text:
        return 4
    if "fairly important" in text:
        return 3
    if "slightly important" in text:
        return 2
    if "not important at all" in text or "not important" in text:
        return 1
    if "important" in text:
        return 4
    return np.nan

importance_cols = [
    "website_quality_importance",
    "security_privacy_importance",
    "product_range_importance",
    "convenience_importance",
    "delivery_importance"
]

for col in importance_cols:
    score_col = col + "_score"
    shopping_data[score_col] = shopping_data[col].apply(clean_likert_answer)

shopping_data[[c for c in shopping_data.columns if c.endswith("_score")]].head()

age_mapping = {
    "18 - 24": 21,
    "25 - 34": 30,
    "35 - 44": 40,
    "45 or over": 50
}
shopping_data["age_midpoint"] = shopping_data["age_group"].map(age_mapping)

frequency_mapping = {
    "Not at all": 0,
    "Annually": 1,
    "Monthly": 2,
    "Weekly": 3
}
shopping_data["shopping_frequency_score"] = shopping_data["shopping_frequency"].map(frequency_mapping)

shopping_data["frequent_shopper"] = (shopping_data["shopping_frequency_score"] >= 2).astype(int)

shopping_data["gender_female"] = (shopping_data["gender"] == "Female").astype(int)
shopping_data["pref_online"] = (shopping_data["shopping_preference"] == "Online Shopping").astype(int)

shopping_data[[
    "age_group", "age_midpoint",
    "shopping_frequency", "shopping_frequency_score",
    "frequent_shopper",
    "gender", "gender_female",
    "shopping_preference", "pref_online"
]].head()

print("Frequent shopper counts:")
print(shopping_data["frequent_shopper"].value_counts())

print("\nFrequent shopper proportions:")
print(shopping_data["frequent_shopper"].value_counts(normalize=True))

print("\nGender proportions:")
print(shopping_data["gender"].value_counts(normalize=True))

print("\nPreference proportions:")
print(shopping_data["shopping_preference"].value_counts(normalize=True))

gender_freq_table = pd.crosstab(shopping_data["gender"], shopping_data["frequent_shopper"])
print("Gender vs frequent shopper table:\n", gender_freq_table, "\n")

female_row = gender_freq_table.loc["Female"]
male_row = gender_freq_table.loc["Male"]

p_female = shopping_data["gender"].value_counts(normalize=True)["Female"]
p_frequent = shopping_data["frequent_shopper"].value_counts(normalize=True)[1]

p_frequent_given_female = female_row[1] / female_row.sum()
p_female_given_frequent = female_row[1] / gender_freq_table[1].sum()

print(f"P(Female) = {p_female:.3f}")
print(f"P(Frequent shopper) = {p_frequent:.3f}")
print(f"P(Frequent | Female) = {p_frequent_given_female:.3f}")
print(f"P(Female | Frequent) = {p_female_given_frequent:.3f}")

sns.countplot(x="gender", data=shopping_data)
plt.title("Gender distribution")
plt.xlabel("Gender")
plt.ylabel("Number of respondents")
plt.show()

sns.countplot(
    x="shopping_frequency",
    data=shopping_data,
    order=["Not at all", "Annually", "Monthly", "Weekly"]
)
plt.title("How often do you shop online?")
plt.xlabel("Shopping frequency")
plt.ylabel("Number of respondents")
plt.show()

sns.countplot(x="shopping_preference", data=shopping_data)
plt.title("Online vs In-store shopping preference")
plt.xlabel("Preference")
plt.ylabel("Number of respondents")
plt.show()

sns.countplot(
    x="age_group",
    data=shopping_data,
    order=["18 - 24", "25 - 34", "35 - 44", "45 or over"]
)
plt.title("Age group distribution")
plt.xlabel("Age group")
plt.ylabel("Number of respondents")
plt.show()

score_cols = [
    "website_quality_importance_score",
    "security_privacy_importance_score",
    "product_range_importance_score",
    "convenience_importance_score",
    "delivery_importance_score"
]

mean_scores = shopping_data[score_cols].mean().sort_values(ascending=False)
print(mean_scores)

sns.barplot(x=mean_scores.values, y=mean_scores.index)
plt.title("Average importance score for each factor (1–5)")
plt.xlabel("Mean importance score")
plt.ylabel("Factor")
plt.xlim(0, 5)
plt.show()

corr_columns = score_cols + ["shopping_frequency_score"]
corr_matrix = shopping_data[corr_columns].corr()

print("Correlation with shopping_frequency_score:\n")
print(corr_matrix["shopping_frequency_score"])

sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation between importance factors and shopping frequency")
plt.show()

from scipy.stats import chi2_contingency

gender_freq_table = pd.crosstab(shopping_data["gender"], shopping_data["frequent_shopper"])
chi2_val, p_val, dof, expected_table = chi2_contingency(gender_freq_table)

print("Gender vs frequent shopper contingency table:\n", gender_freq_table, "\n")
print("Expected counts under independence:\n", pd.DataFrame(expected_table,
      index=gender_freq_table.index, columns=gender_freq_table.columns))

print(f"\nChi-square statistic: {chi2_val:.3f}")
print(f"Degrees of freedom: {dof}")
print(f"P-value: {p_val:.3f}")

pref_freq_table = pd.crosstab(shopping_data["shopping_preference"],
                              shopping_data["frequent_shopper"])
chi2_val2, p_val2, dof2, expected_table2 = chi2_contingency(pref_freq_table)

print("Preference vs frequent shopper contingency table:\n", pref_freq_table, "\n")
print("Expected counts under independence:\n", pd.DataFrame(expected_table2,
      index=pref_freq_table.index, columns=pref_freq_table.columns))

print(f"\nChi-square statistic: {chi2_val2:.3f}")
print(f"Degrees of freedom: {dof2}")
print(f"P-value: {p_val2:.3f}")

from scipy.stats import chisquare

freq_counts = shopping_data["shopping_frequency"].value_counts().reindex(
    ["Not at all", "Annually", "Monthly", "Weekly"]
)
print("Observed counts:\n", freq_counts)

expected_each = len(shopping_data) / 4
expected_counts = np.repeat(expected_each, 4)

chi2_gof, p_gof = chisquare(freq_counts.values, f_exp=expected_counts)

print("\nExpected counts under uniform distribution:", expected_counts)
print(f"\nChi-square GOF statistic: {chi2_gof:.3f}")
print(f"P-value: {p_gof:.3e}")

print("Number of respondents:", len(shopping_data))
print("Frequent shoppers (Monthly or Weekly):", shopping_data['frequent_shopper'].sum())
print("Non-frequent shoppers (Annually or Not at all):",
      (shopping_data['frequent_shopper'] == 0).sum())

print("\nMost common age group:", shopping_data['age_group'].mode()[0])
print("Most common shopping frequency:", shopping_data['shopping_frequency'].mode()[0])

print("\nOnline vs In-store preference:\n",
      shopping_data['shopping_preference'].value_counts())